const MARVEL_API_BASE_URL = 'https://gateway.marvel.com/v1/public';
const MARVEL_CHARACTER_API = '/characters';
const SUCCESS_API_STATUS = [200, 304];
const TEN_MINUTES = 600;
const THREE_MINUTES = 180;
export { MARVEL_API_BASE_URL, MARVEL_CHARACTER_API, SUCCESS_API_STATUS, TEN_MINUTES, THREE_MINUTES }